# Generated by Django 5.1.6 on 2025-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_dispatch_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='text',
            field=models.TextField(help_text='Вы можете использовать переменные: ${id}, ${username}, ${first_name}, ${last_name}', verbose_name='Текст'),
        ),
    ]
